import type { Metadata } from "next";
import { Geist, Geist_Mono, Share_Tech_Mono } from "next/font/google";
import Header from "./(layout)/header";
import EffectsOverlay from "./(map)/components/EffectsOverlay";
import InitialLoadingGate from "./(map)/components/InitialLoadingGate";
import SettingsPopover from "./(layout)/SettingsPopover";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const shareTechMono = Share_Tech_Mono({
  variable: "--font-share-tech-mono",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${shareTechMono.variable} antialiased m-0 h-screen overflow-hidden relative`}
      >
        <InitialLoadingGate>
          <div className="flex h-full w-full flex-col overflow-hidden">
            <Header />
            <div className="w-full flex-1 min-h-0">{children}</div>
          </div>
          <EffectsOverlay />
          
         <SettingsPopover />
        </InitialLoadingGate>
      </body>
    </html>
  );
}
